name: Go CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build
        run: go build -o onlyflick ./cmd/api

      - name: Run tests
        run: go test ./...

      - name: Docker Build & Push (optional if Railway auto-builds)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: onlyflick:latest
