name: CI/CD – Build & Deploy OnlyFlick API

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/onlyflick-api:latest

      - name: Setup SSH to VPS
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy on VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/onlyflick-api:latest
            docker stop onlyflick || true
            docker rm onlyflick || true
            docker run -d --name onlyflick -p 8080:8080 --env-file .env ${{ secrets.DOCKER_USERNAME }}/onlyflick-api:latest
          EOF
